// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the authenticated ENAZIZI user id and email.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const info = { user_id: ctx.getUserId(), email: ctx.getUserEmail() };
    return {
      content: [{ type: "text", text: JSON.stringify(info) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/list-recent-errors.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.4";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_recent_errors_default = defineTool2({
  name: "list_recent_errors",
  title: "List recent study errors",
  description: "Return the signed-in user's most recent items from the ENAZIZI Banco de Erros (error_bank), newest first. Useful to review weak topics.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(10).describe("Maximum number of errors to return (1-50)."),
    only_undominated: z.boolean().default(true).describe("If true, return only errors the user has not yet mastered (dominado = false).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, only_undominated }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    let q = sb.from("error_bank").select("id, tema, subtema, categoria_erro, motivo_erro, vezes_errado, dominado, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (only_undominated) q = q.eq("dominado", false);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { errors: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-memory.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.105.4";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_memory_default = defineTool3({
  name: "search_tutor_memory",
  title: "Search tutor memory",
  description: "Full-text search in the ENAZIZI tutor_knowledge_memory for entries visible to the signed-in user (own entries + promoted global knowledge). Returns question, topic, and a short answer summary.",
  inputSchema: {
    query: z2.string().trim().min(2).describe("Search text (matches topic, subtopic, question, or answer summary)."),
    limit: z2.number().int().min(1).max(25).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    const pattern = `%${query}%`;
    const { data, error } = await sb.from("tutor_knowledge_memory").select("id, topic, subtopic, specialty, question_original, answer_summary, quality_score, reuse_count, scope").or(
      `question_original.ilike.${pattern},answer_summary.ilike.${pattern},topic.ilike.${pattern},subtopic.ilike.${pattern}`
    ).order("quality_score", { ascending: false }).limit(limit);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-flashcard.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.105.4";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_flashcard_default = defineTool4({
  name: "create_flashcard",
  title: "Create flashcard",
  description: "Create a new flashcard in the ENAZIZI deck for the signed-in user. Use short, high-yield medical Q&A in pt-BR.",
  inputSchema: {
    question: z3.string().trim().min(3),
    answer: z3.string().trim().min(1),
    topic: z3.string().trim().min(1).describe("Clinical topic, e.g. 'Cardiologia'."),
    subtopic: z3.string().trim().optional(),
    explanation: z3.string().trim().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ question, answer, topic, subtopic, explanation }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    const { data, error } = await sb.from("flashcards").insert({
      user_id: ctx.getUserId(),
      question,
      answer,
      topic,
      subtopic: subtopic ?? null,
      explanation: explanation ?? null,
      source: "mcp"
    }).select("id, question, topic, subtopic, created_at").single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Flashcard criado: ${data.id}` }],
      structuredContent: { flashcard: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "qszsyskumcmuknumwxtk";
var mcp_default = defineMcp({
  name: "enazizi-mcp",
  title: "ENAZIZI",
  version: "0.1.0",
  instructions: "Ferramentas do ENAZIZI (plataforma de estudos m\xE9dicos). Use `whoami` para confirmar identidade, `list_recent_errors` para revisar o Banco de Erros do aluno, `search_tutor_memory` para consultar a mem\xF3ria pedag\xF3gica, e `create_flashcard` para adicionar cards ao deck do aluno. Todas as opera\xE7\xF5es rodam como o usu\xE1rio autenticado e respeitam RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_recent_errors_default, search_memory_default, create_flashcard_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
