-- Seed ai_video_lessons (with media_status set to 'ready')
INSERT INTO public.ai_video_lessons (id, title, specialty, topic, subtopic, description, video_url, thumbnail_url, duration_seconds, status, visibility, difficulty_level, media_status, published_at, is_gold_content, created_at, updated_at)
VALUES 
(gen_random_uuid(), 'Insuficiência Cardíaca: Diagnóstico e Manejo', 'Cardiologia', 'Insuficiência Cardíaca', 'Diagnóstico', 'Abordagem completa da IC seguindo as diretrizes mais recentes.', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'https://images.unsplash.com/photo-1628348068343-c6a848d2b6dd?w=800', 1200, 'published', 'public', 'intermediate', 'ready', now(), true, now(), now()),
(gen_random_uuid(), 'Puericultura: Marcos do Desenvolvimento', 'Pediatria', 'Puericultura', 'Desenvolvimento', 'Principais marcos do desenvolvimento neuropsicomotor na infância.', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'https://images.unsplash.com/photo-1581594693702-fbdc51b2ad42?w=800', 900, 'published', 'public', 'beginner', 'ready', now(), false, now(), now()),
(gen_random_uuid(), 'Atendimento Inicial ao Politraumatizado', 'Cirurgia Geral', 'Trauma', 'ABCDE', 'Protocolo ATLS 10ª edição para abordagem inicial.', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'https://images.unsplash.com/photo-1516549655169-df83a0774514?w=800', 1800, 'published', 'public', 'advanced', 'ready', now(), true, now(), now()),
(gen_random_uuid(), 'Sepse e Choque Séptico: Sepsis-3', 'Infectologia', 'Sepse', 'Protocolo', 'Definições e conduta imediata no paciente com sepse.', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=800', 1500, 'published', 'public', 'intermediate', 'ready', now(), true, now(), now()),
(gen_random_uuid(), 'Crise Asmática na Emergência', 'Pneumologia', 'Asma', 'Crise Aguda', 'Manejo passo a passo da exacerbação de asma em adultos.', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800', 1100, 'published', 'public', 'intermediate', 'ready', now(), false, now(), now()),
(gen_random_uuid(), 'Pré-natal de Baixo Risco', 'Ginecologia e Obstetrícia', 'Obstetrícia', 'Pré-natal', 'Exames, suplementação e acompanhamento de rotina.', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'https://images.unsplash.com/photo-1518152006812-edab29b069ac?w=800', 1300, 'published', 'public', 'beginner', 'ready', now(), false, now(), now()),
(gen_random_uuid(), 'Diabetes Mellitus Tipo 2: Novas Drogas', 'Endocrinologia', 'Diabetes', 'Tratamento', 'Inibidores de SGLT2 e análogos de GLP-1 na prática clínica.', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'https://images.unsplash.com/photo-1576086213369-97a306d36557?w=800', 1400, 'published', 'public', 'intermediate', 'ready', now(), true, now(), now()),
(gen_random_uuid(), 'Antibioticoterapia nas Pneumonias Comunitárias', 'Infectologia', 'Pneumonia', 'Tratamento', 'Escolha empírica baseada nos guidelines da SBPT.', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'https://images.unsplash.com/photo-1584362946045-121f8af9214d?w=800', 1000, 'published', 'public', 'intermediate', 'ready', now(), false, now(), now()),
(gen_random_uuid(), 'Abdome Agudo Inflamatório: Apendicite', 'Cirurgia Geral', 'Abdome Agudo', 'Apendicite', 'Diagnóstico clínico, por imagem e tática cirúrgica.', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'https://images.unsplash.com/photo-1551076805-e1869033e561?w=800', 1600, 'published', 'public', 'intermediate', 'ready', now(), true, now(), now()),
(gen_random_uuid(), 'Emergências Psiquiátricas: Agitação', 'Psiquiatria', 'Emergências', 'Agitação Psicomotora', 'Contenção química e física segura no pronto-atendimento.', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'https://images.unsplash.com/photo-1527137341206-1a2bd8151397?w=800', 950, 'published', 'public', 'intermediate', 'ready', now(), false, now(), now());

-- Seed enaflix_content
INSERT INTO public.enaflix_content (id, title, description, specialty, content_type, video_url, thumbnail_url, duration_minutes, difficulty, is_published, created_at, updated_at)
VALUES 
(gen_random_uuid(), 'Masterclass: ECG de Elite', 'Domine o eletrocardiograma do básico ao avançado para provas.', 'Cardiologia', 'video', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'https://images.unsplash.com/photo-1559757175-5700dde675bc?w=800', 120, 'dificil', true, now(), now()),
(gen_random_uuid(), 'Flash-Review: Ginecologia e Obstetrícia', 'Os 10 temas mais cobrados em GO em menos de 30 minutos.', 'Ginecologia e Obstetrícia', 'aula', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'https://images.unsplash.com/photo-1518152006812-edab29b069ac?w=800', 28, 'facil', true, now(), now()),
(gen_random_uuid(), 'Simulado Comentado: ENARE 2024', 'Resolução detalhada da última prova do ENARE.', 'Clínica Médica', 'video', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800', 180, 'intermediario', true, now(), now()),
(gen_random_uuid(), 'Guia de Prescrição: Antibióticos', 'Como prescrever os principais antibióticos na enfermaria.', 'Infectologia', 'video', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=800', 45, 'intermediario', true, now(), now()),
(gen_random_uuid(), 'Emergências Clínicas: O Guia Prático', 'Protocolos rápidos para as situações mais comuns no plantão.', 'Medicina de Emergência', 'video', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'https://images.unsplash.com/photo-1516549655169-df83a0774514?w=800', 60, 'intermediario', true, now(), now()),
(gen_random_uuid(), 'Inteligência IA na Medicina', 'Como utilizar as novas ferramentas cognitivas nos seus estudos.', 'Geral', 'aula', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800', 35, 'facil', true, now(), now()),
(gen_random_uuid(), 'Cirurgia do Trauma: Casos Reais', 'Discussão de casos complexos de trauma abdominal e torácico.', 'Cirurgia Geral', 'video', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800', 55, 'dificil', true, now(), now()),
(gen_random_uuid(), 'Pediatria: Doenças Exantemáticas', 'Diagnóstico diferencial visual das principais viroses infantis.', 'Pediatria', 'video', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'https://images.unsplash.com/photo-1581594693702-fbdc51b2ad42?w=800', 40, 'intermediario', true, now(), now()),
(gen_random_uuid(), 'Radiologia para o Clínico', 'Identificação de padrões em RX e TC de tórax na emergência.', 'Clínica Médica', 'video', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'https://images.unsplash.com/photo-1584362946045-121f8af9214d?w=800', 50, 'intermediario', true, now(), now()),
(gen_random_uuid(), 'Gestão de Carreira Médica', 'Planejamento pós-residência e mercado de trabalho em 2025.', 'Geral', 'podcast', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'https://images.unsplash.com/photo-1527137341206-1a2bd8151397?w=800', 42, 'facil', true, now(), now());
